Description: Go Bot Arena Certificate
Parameters:
  DomainName:
    Description: go-bot-areana
    Type: String
  HostedZoneId:
    Description: The Hosted ID to validate the certificate
    Type: String
Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub "*.${DomainName}"
      SubjectAlternativeNames: 
        - !Ref DomainName
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId
      Tags:
        - Key: Name
          Value: !Ref DomainName
