apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: go-bot-arean
        image: 007469101954.dkr.ecr.us-east-1.amazonaws.com/go-bot-arean:latest
        ports:
        - containerPort: 80
