apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-bot-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    spec:
      containers:
      - name: go-bot
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
