apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

# apiVersion: v1
# kind: Service
# metadata:
#   name: go-bot-service
# spec:
#   selector:
#     app: go-bot
#   ports:
#     - protocol: TCP
#       port: {{ .Values.service.port }}  # 80
#       targetPort:  {{ .Values.service.targetPort }}  #  5000